version: 2.1
jobs:
  build:
    docker:
      - image: centos:latest 
    steps:
      - checkout
      - run:
          name: Update OS and Install packages
          command: |
            yum -y update
            yum -y install epel-release
            yum -y install python-pip
      - run:
          name: Install Ionic SDK
          command: |
            pip install --upgrade pip
            pip install ionicsdk
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user # install AWS CLI
            pip install --upgrade --user awscli # upgrade to newest AWS CLI
      - run: 
          name: Canary
          command: |
            cat /etc/redhat-release
            python -V 
            pip show ionicsdk
            ~/.local/bin/aws --version
      - run:
          name: Import Profile
          command: |
            mkdir ../.ionicsecurity
            echo $IONIC_PROFILE | base64 --decode > ../.ionicsecurity.pw
      - run:
          name: profiles
          command: |
            cd python/sdk-basics/profiles
            python main.py
      - run:
          name: ionic cipher
          command: |
            cd ../ionic-ciphers
            python main.py
